### ISSUE TITLE
Determine which component library to use

### ISSUE THREAD

**Issue by alexstojda** [alexstojda/pinman#13]
Ideas:

- https://rsuitejs.com/resources/templates/
- https://chakra-ui.com/docs/components/
- https://github.com/mui/material-ui
- https://geist-ui.dev/en-us/components

**Comment by philippelorange** [comment]
Haven’t worked with much apart from material UI. However I’d be interested in looking into Chakra or Mantine, which both seem promising and more importantly have decent documentation

**Comment by alexstojda** [comment]
Good points! Was also leaning towards Chakra to try something new this project, I've also used MUI in a few projects before. 

Chakra it is!
